# Basic Information 
title: Ebru Evcen
position: PhD candidate in Linguistics
affiliation: UC San Diego
affiliation_link: https://linguistics.ucsd.edu
#affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: eevcen (at) ucsd.edu

# Search Engine Optimization (SEO)
keywords: evcen ebru, ebru evcen, evcen, ebruevcen
canonical: https://ebruevcen.github.io/
description: Ebru Evcen is a PhD candidate in Linguistics at UC San Diego. Her research lies in psycholinguistics and experimental pragmatics.


# The option is used to show the last update time.
enable_last_update: true

# Links
#link_type: text #text/icon
cv_link: .assets/files/curriculum_vitae.pdf
github_link: https://github.com/ebruevcen
linkedin: https://www.linkedin.com/in/ebru-evcen-10916498/
twitter: https://twitter.com/evcen_ebru
osf: https://osf.io/jtcmz 

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png


# Footnote
footnote: Powered by Jekyll and Minimal Light theme.
footnote_link: https://github.com/yaoyao-liu/minimal-light
enable_footnote: true

remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
